spring.application.name=backend-java
# 允许单个文件的最大值 (例如 50MB)
spring.servlet.multipart.max-file-size=100MB
# 单次请求的总文件大小
spring.servlet.multipart.max-request-size=100MB

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/academic_db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true